/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital;

import java.sql.Statement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author sohail
 */
public class login extends javax.swing.JFrame {
 Connection con=null;
 Statement st=null;
 ResultSet rs=null;
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        label1 = new java.awt.Label();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(981, 565));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 170, 33));

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jLabel1.setText("username");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 120, 33));

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jLabel2.setText("password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 120, 23));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 170, 30));

        jButton1.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jButton1.setText("login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 430, 100, -1));

        jComboBox1.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RECEPTIONIST", "GENERAL DOCTOR", "HEART SPECIALIST", "ENT SPECIALIST", "SKIN SPECIALIST", "DENTIST", "ADMIN", " ", " " }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 190, -1));

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Lucida Bright", 1, 36)); // NOI18N
        label1.setName(""); // NOI18N
        label1.setText("HOSPITAL MANAGEMENT SYSTEM");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));
        label1.getAccessibleContext().setAccessibleName("");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/patient_form.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 1530, 520));

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    database db= new database();
      int id=0;
      boolean login =false;
     try{
       con=db.createdatabase();
      st=con.createStatement();
     rs=st.executeQuery("select * from login where username='"+jTextField1.getText()+"'and password='"+jTextField2.getText()+"' ");
       while(rs.next()){
          
             JOptionPane.showMessageDialog(this,"Login Successful "); 
         login=true;
      }
    }
    catch (SQLException e )
        
     {
           JOptionPane.showMessageDialog(this,e); 
         
     }
     if(login){
                if(jComboBox1.getSelectedIndex()==0){
                 Receptionist ap=new Receptionist();
                   //this.hide();
                   ap.show();
    }//GEN-LAST:event_jButton1ActionPerformed
            if(jComboBox1.getSelectedIndex()==1){
                 General_Doctor gp=new General_Doctor();
                   this.hide();
                   gp.show();
    } 
           if(jComboBox1.getSelectedIndex()==3){
                 ENT_SPECIALIST s=new ENT_SPECIALIST();
                   this.hide();
                   s.show();
    }
              if(jComboBox1.getSelectedIndex()==4){
                 SKIN_SPECIALIST s=new SKIN_SPECIALIST();
                   this.hide();
                   s.show();
    }
                 if(jComboBox1.getSelectedIndex()==2){
                 HEART_SPECIALIST s=new HEART_SPECIALIST();
                   this.hide();
                   s.show();
    }
                    if(jComboBox1.getSelectedIndex()==5){
                 DENTIST s=new DENTIST();
                   this.hide();
                   s.show();
    }
                                   if(jComboBox1.getSelectedIndex()==6){
                 Admin s=new Admin();
                   this.hide();
                   s.show();
    }
     }
     else
            JOptionPane.showMessageDialog(this,"invalid login or password"); 
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
